package com.bibek.bytestream.internal.download

import com.bibek.bytestream.internal.utils.getUniqueId
import kotlinx.serialization.Serializable

/**
 * Data class representing a request to download a file.
 *
 * @property downloadUrl The URL of the file to be downloaded.
 * @property destinationPath The local file system path where the file will be saved.
 * @property outputFileName The name of the file to save the downloaded content as.
 * @property requestTag An optional tag for the download request, can be used for identifying or grouping requests.
 * @property requestId A unique identifier for the download request, generated based on the download URL, destination path, and output file name.
 * @property requestHeaders A map of custom headers to include in the request for downloading the file.
 * @property additionalInfo Any extra information related to the download request.
 * @property metadata Additional metadata related to the download request (e.g., file type, size).
 */
@Serializable
data class FileDownloadRequest(
    /**
     * The URL of the file to be downloaded.
     */
    val downloadUrl: String = "",

    /**
     * The local file system path where the file will be saved.
     */
    val destinationPath: String = "",

    /**
     * The name of the file to save the downloaded content as.
     */
    val outputFileName: String = "",

    /**
     * An optional tag for the download request, can be used for identifying or grouping requests.
     */
    val requestTag: String = "",

    /**
     * A unique identifier for the download request. It is generated by combining the download URL, destination path, and output file name.
     */
    val requestId: Int = getUniqueId(downloadUrl, destinationPath, outputFileName),

    /**
     * A map of custom headers to include in the request for downloading the file.
     */
    val requestHeaders: HashMap<String, String> = hashMapOf(),

    /**
     * Any extra information related to the download request.
     */
    val additionalInfo: String = "",

    /**
     * Additional metadata related to the download request (e.g., file type, size).
     */
    val metadata: String = ""
)
